### ISSUE TITLE
Waypoint aur

### ISSUE THREAD

**Issue by MinmoTech** [sebastiangaiser/waypoint-docker#1]
Was wäre hiermit? :grin: 
![image](https://user-images.githubusercontent.com/25890405/110542895-eb85f880-8129-11eb-9938-6131ab6db75c.png)

**Comment by sebastiangaiser** [comment]
That's not the latest version of waypoint. I corrected the readme ;)

**Comment by MinmoTech** [comment]
![1615478839](https://user-images.githubusercontent.com/25890405/110817277-6bc46f00-828c-11eb-89a8-be0c16ca36b2.png)

You can mark packages as out of date here :v:
